///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsWords = 'assets/words.txt';
  static const String iconsFa = 'assets/icons/fa.png';
  static const String iconsKnowledgeMap = 'assets/icons/knowledge_map.svg';
  static const String iconsLightBulb = 'assets/icons/light_bulb.png';
  static const String iconsSpeaker = 'assets/icons/speaker.svg';

}
